name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    if: github.event.label.name == 'CI' || contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        curl -sSf https://rye.astral.sh/get | bash
        source "$HOME/.rye/env"
        rye sync
      
    - name: Run tests
      run: |
        python -m pytest tests/
        
    - name: Build documentation
      run: |
        cd docs
        make html