name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    types: [labeled]

jobs:
  test:
    if: github.event.label.name == 'CI' || contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install and configure Rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_VERSION="0.1.0" RYE_INSTALL_OPTION="--yes" bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: rye sync
        
    - name: Run tests
      run: python -m pytest tests/
        
    # - name: Build documentation
    #   run: |
    #     cd docs
    #     make html