name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    if: github.event.label.name == 'CI' || contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Fluent CI CLI
      uses: fluentci-io/setup-fluentci@v5
      with:
        wasm: true
        plugin: rye
        args: |
          setup

    - name: Show rye version
      run: |
        type rye
        rye --version

    - name: Install dependencies
      run: |
        rye sync

    - name: Run tests
      run: |
        python -m pytest tests/

    - name: Build documentation
      run: |
        cd docs
        make html