name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    if: github.event.label.name == 'CI' || contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_VERSION="0.1.0" RYE_INSTALL_OPTION="--yes" bash
        source "$HOME/.rye/env"

    - name: Show rye version
      run: |
        type rye
        rye --version

    - name: Install dependencies
      run: |
        rye sync

    - name: Run tests
      run: |
        python -m pytest tests/

    # - name: Build documentation
    #   run: |
    #     cd docs
    #     make html